# Generated by Django 5.0.3 on 2024-03-11 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_info',
            old_name='descrition',
            new_name='description',
        ),
    ]
